# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dchantse <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/24 21:51:35 by dchantse          #+#    #+#              #
#    Updated: 2018/10/24 22:13:36 by dchantse         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FLAGS = -Wall -Wextra -Werror
SRCS = display_file.c
NAME = ft_display_file

all: make

make:
	gcc $(FLAGS) $(SRCS) -o $(NAME)
clean:
	rm -rf all
fclean: clean
	rm -rf $(NAME)
